# This workflow performs continuous integration (CI).
# This workflow will build the container image for amd64 arch. (as a basic build test)
name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - "CODEOWNERS"
      - "agent/docs/**"
      - "server/docs/**"
      - "agent/scripts/**"
      - "server/scripts/**"
      # - "assets/**"
      # - "scripts/**"
      # - "src/testclient/scripts/**"
      # - ".all-contributorsrc"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - "CODEOWNERS"
      - "agent/docs/**"
      - "server/docs/**"
      - "agent/scripts/**"
      - "server/scripts/**"
      # - "assets/**"
      # - "scripts/**"
      # - "src/testclient/scripts/**"
      # - ".all-contributorsrc"

jobs:
  # The job key (i.e., ID) is "build-agent-source-code"
  build-agent-source-code:
    # Job name is "Build agent source code"
    # This job runs on Ubuntu-latest (Ubuntu 22.04 LTS checked on 2023-12-13)
    # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    name: Build agent source code
    strategy:
      matrix:
        go-version: ["1.24.0"]
        os: [ubuntu-22.04, windows-2022]
        #os: [ubuntu-22.04, ubuntu-20.04, windows-2022, windows-2019]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}

      - name: Build
        run: cd agent/ && make build-only

  # The job key (i.e., ID) is "build-server-source-code"
  build-server-source-code:
    name: Build server source code
    strategy:
      matrix:
        go-version: ["1.24.0"]
        os: [ubuntu-22.04, windows-2022]
        #os: [ubuntu-22.04, ubuntu-20.04, windows-2022, windows-2019]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
      - name: Build
        run: cd server/ && make build-only

  # The job key is "build-server-container-image"
  build-server-container-image:
    # Job name is "Build a container image for cm-honeybee server"
    name: Build a container image for cm-honeybee server

    # This job runs on Ubuntu-latest (Ubuntu 22.04 LTS checked on 2023-12-13)
    # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-22.04
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build
        env:
          IMAGE_NAME: ${{ github.event.repository.name }}
        run: cd server/ && docker build . --file Dockerfile --tag $IMAGE_NAME
